# Generated by Django 5.2 on 2025-04-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_coach_user_tariff_delete_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=10),
        ),
    ]
