# Generated by Django 5.2 on 2025-04-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tariff',
            new_name='rate',
        ),
    ]
